title: Gothic Mody
description: Twoje źródło informacji na temat modyfikacji dla gry Gothic! Wywiady, recenzje, opisy i wiele wiele innych.
theme: null
layouts_dir: ./server/templates
includes_dir: ./server/templates
paginate: 4
paginate_path: "/:num"
permalink: /:year/:month/:day/:title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      categories: "newsy"
  -
    scope:
      path: ""
      type: "category"
    values:
      layout: "category"
  -
    scope:
      path: "download"
      type: "pages"
    values:
      layout: "redirect"
  -
    scope:
      path: "gothic-i"
      type: "pages"
    values:
      layout: "mod-page"
  -
    scope:
      path: "gothic-ii"
      type: "pages"
    values:
      layout: "mod-page"
collections:
  category:
    output: true
plugins:
  - github-pages